entities:

  ApplicationDataObjects:
    title: Объекты данных приложений
    description: "Объекты данных приложений"
    presentations:
      blank:
        title: Основная карточка Объекты данных приложений
        type: markdown
        template: templates/application_data_object_card.md
        source: >
          (
          
            $AppDataObject_Id := $params.id; /*"Romashka.ApplicationDataObject.EK_ASUFR3_1C_ERP.Organizations"*/
            
            $Datalake := $;
            
            /* Описание карточки приложения и сервиса */
            $ComponentCardSystem  := Constants.ComponentCard.System;
            
            /* Описание карточки компонента */
            $ComponentCardDefault := Constants.ComponentCard.Default;
            
            /* Поиск приложения/сервиса выполянется по ключу, чтобы не использовать components.$spread() + [отбор по ID], */
            /* так как на большом объеме озера данных будут наблюдаться задржки обработки данных */
            $FoundAppDataObj := $lookup(ApplicationDataObjects, $AppDataObject_Id);
            
            {
              "id": $AppDataObject_Id,
              "title": $FoundAppDataObj.title,
              "description": $FoundAppDataObj.description,
              "system_id": $FoundAppDataObj.system,
              "system_link": $ComponentCardSystem & $FoundAppDataObj.system,
              "system_title": $lookup($Datalake.components, $FoundAppDataObj.system).title,
              "sybsystem_link": $ComponentCardDefault & $FoundAppDataObj.sybsystem,
              "sybsystem_title": $lookup($Datalake.components, $FoundAppDataObj.sybsystem).title,
              "type": $FoundAppDataObj.type,
              "state": $FoundAppDataObj.state,
              "state_update_date": $FoundAppDataObj.state_update_date,
              "owner": $FoundAppDataObj.owner,
              "division_owner": $FoundAppDataObj.division_owner,
              "division_owner_link": $ComponentCardDefault & $FoundAppDataObj.division_owner,
              "division_owner_title": $lookup($Datalake.components, $FoundAppDataObj.division_owner).title,
              "count_business_data_obj": $count($FoundAppDataObj.business_Objects)
            }
  
          )
      filteredBy_SystemID:
        title: Таблица объектов приложения, отфильтрованных по ID приложения/сервиса
        type: table
        headers:
          - value: title
            text: Объект приложения/сервиса
            sortable: true
            link: link_id
          - value: description
            text: Описание
          - value: type
            text: Вид
          - value: state
            text: Статус
            sortable: true
          - value: state_update_date
            text: Дата актуализации статуса
            sortable: true
        origin: ApplicationDataObjects.dataset.ListOfApplicationDataObjects
        source: >
          (
            $SystemID := $params.SystemID != "" ? $params.SystemID : "";
            [$[$contains(system_id, $SystemID)]]
          )
      filteredBy_BusinessObjectID:
        title: Таблица объектов приложений, отфильтрованных по ID бизнес объекта
        type: table
        headers:
          - value: System_title
            text: Приложение/Сервис
            link: System_link
          - value: AppDataObject_title
            text: Объект приложения/сервиса
            link: AppDataObject_link
            sortable: true
          - value: AppDataObject_description
            text: Описание
          - value: AppDataObject_state
            text: Статус
            sortable: true
          - value: AppDataObject_state_update_date
            text: Дата актуализации статуса
            sortable: true
        origin: ApplicationDataObjects.dataset.MainListOfApplicationDataObjects
        source: >
          (
            $id := $params.id != "" ? $params.id : "";
            [$[BusinessObject_id=$id]]
          )
      filteredBy_AppDataObjID_and_SystemID:
        title: Таблица бизнес сущностей, отфильтрованных по объекту приложения и приложению
        type: table
        headers:
          - value: BusinessObject_title
            text: Бизнес-сущность
            link: BusinessObject_link
            sortable: true
          - value: BusinessObject_description
            text: Описание
          - value: BusinessObject_state
            text: Статус
            sortable: true
          - value: BusinessObject_state_update_date
            text: Дата актуализации статуса
            sortable: true
        origin: ApplicationDataObjects.dataset.MainListOfApplicationDataObjects
        source: >
          (
            $system_id := $params.system_id != "" ? $params.system_id : "";
            $app_data_id := $params.app_data_id != "" ? $params.app_data_id : "";
            [$[System_id=$system_id and AppDataObject_id=$app_data_id]]
          ) 
