components:

  Romashka.Systems.Supporting:
    title: Обеспечивающие (поддерживающие) системы
    entity: component

contexts:

  Romashka.Systems.Supporting:
    title: "Обеспечивающие (поддерживающие) системы"
    location: "Ромашка/Архитектурные схемы/Уровень 2/Обеспечивающие (поддерживающие) системы"
    extra-links: true
    components:
      - Romashka.Systems.Supporting.*