#components:

#  Romashka.Systems:
#    title: Приложения и сервисы
#    entity: component

  # Контура автоматизации предприятия

#  Romashka.Systems.FinancialManagement:
#    title: Финансовый контур
#    entity: component

#  Romashka.Systems.DocumentManagement:
#    title: Документооборот (ЭДО, ЮЗЭДО, ВКЭДО)
#    entity: component

#  Romashka.Systems.HRManagement:
#    title: Расчет заработной платы и управление персоналом
#    entity: component

#  Romashka.Systems.VehicleManagement:
#    title: Управление автотранспортом
#    entity: component

#  Romashka.Systems.Technological:
#    title: Технологический контур
#    entity: component

#  Romashka.Systems.Supporting:
#    title: Обеспечивающие (поддерживающие) системы
#    entity: component
#
#  Romashka.Systems.ArchitectureManagement:
#    title: Управление архитектурой
#    entity: component

#  Romashka.Systems.ReportingSystems:
#    title: Консолидированная отчетность
#    entity: component