dictionaries:

  settings.applications_category:
    title: Категория приложений
    description: Справочник категорий приложения/системы/сервиса
    order: 8120
    link:
    parameters:
      - name: channel_app
        title: Канальные приложения
        description: В этот раздел попадают все приложения/системы/сервисы через которые к нам попадают данные из вне. Например, мобильные приложения, теллеграм каналы и т.д.
        order: 1
        color: blue
      - name: business_app
        title: Бизнес-приложения
        description: В этот раздел попадают все приложения/системы/сервисы, которые требуются бизнесу для выполнения своих процессов и которые находятся в инфраструктуре, которую мы контролируем.
        order: 2
        color: teal
      - name: ext_business_app
        title: Внешние бизнес-приложения
        description: В этот раздел попадают все приложения/системы/сервисы, которые требуются бизнесу для выполнения своих процессов и которые находятся в инфраструктуре, которой мы не управляем.
        order: 3
        color: deep-purple
      - name: it_app
        title: ИТ-приложения
        description: В этот раздел попадают все приложения/системы/сервисы, которые требуются ИТ для выполнения своих процессов и которые находятся в инфраструктуре, которую мы контролируем.
        order: 4
        color: light-green
      - name: ext_it_app
        title: Внешние ИТ-приложения
        description: В этот раздел попадают все приложения/системы/сервисы, которые требуются ИТ для выполнения своих процессов и которые находятся в инфраструктуре, которой мы не управляем.
        order: 5
        color: yellow