components:

  Romashka.Systems.VehicleManagement:
    title: Управление автотранспортом
    entity: component

contexts:

  Romashka.Systems.VehicleManagement:
    title: Управление автотранспортом
    location: "Ромашка/Архитектурные схемы/Уровень 2/Управление автотранспортом"
    extra-links: true
    components:
      - Romashka.Systems.VehicleManagement.*

aspects:

  VehicleManagement:
    title: Транспортные средства
    location: Транспортные средства

  VehicleManagement.Vehicles:
    title: Учет транспортных средств
    location: Учет транспортных средств

  VehicleManagement.ApplicationsRoadTransport:
    title: Учет заявок на автоперевозки
    location: Учет заявок на автоперевозки

  VehicleManagement.Waybills:
    title: Учет путевых листов
    location: Учет путевых листов
