components:

  # Функциональная область

  Romashka.Systems.FinancialManagement:
    title: Финансовый контур
    entity: component

contexts:

  # Конктест функциональной область для схемы

  Romashka.Systems.FinancialManagement:
    title: Финансовый контур
    location: "Ромашка/Архитектурные схемы/Уровень 3/Финансовый контур"
    extra-links: true
    components:
      - Romashka.Systems.FinancialManagement.*

aspects:

  # Функциональность функциональной области

  FinancialManagement:
    title: Финансовый контур
    location: Финансовый контур

  FinancialManagement.RegulatedAccounting:
    title: Регламентированный учет
    location: Регламентированный учет

  FinancialManagement.TaxAccounting:
    title: Налоговый учет
    location: Налоговый учет

  FinancialManagement.ManagementAccounting:
    title: Управленческий учет
    location: Управленческий учет

  FinancialManagement.IFRSAccounting:
    title: Учет по МСФО
    location: Учет по МСФО

  FinancialManagement.TreasuryAccounting:
    title: Казначейский учет
    location: Казначейский учет

  FinancialManagement.MTR:
    title: Управление снабжением (МТР)
    location: Управление снабжением (МТР)