components:

  Romashka.Clusters.Prod:
    title: Сервера продуктивного контура
    entity: collections
    description: "Совокупность версий информационных систем, предназначенных для выполнения процессов, имеющих юридическую значимость"
    extension:
      type: Группа серверов

  Romashka.Clusters.Prod.FinancialManagement:
    title: Сервера финансового контура
    entity: collections
    extension:
      type: Группа серверов функциональной области

  Romashka.Clusters.Prod.DocumentManagement:
    title: Сервера документооборота (ЭДО, ЮЗЭДО, ВКЭДО)
    entity: collections
    extension:
      type: Группа серверов функциональной области

  Romashka.Clusters.Prod.VehicleManagement:
    title: Сервера управления автотранспортом
    entity: collections
    extension:
      type: Группа серверов функциональной области

  Romashka.Clusters.Prod.Other:
    title: Прочие сервера (HR, обеспечивающие системы)
    entity: collections
    extension:
      type: Группа серверов функциональной области

#    #todo список орагнихация в БА, чтобы видеть общий контектс