#contexts:

   # Контекст Управления автотранспортом

#  Romashka.Systems.VehicleManagement:
#    title: Управление автотранспортом
#    location: "Ромашка/Архитектурные схемы/Уровень 3/Управление автотранспортом"
#    extra-links: true
#    components:
#      - Romashka.Systems.VehicleManagement.*

#  Romashka.Systems.VehicleManagement.EK_ASUFR3_1C_YAT:
#    title: ЕК АСУФР-3. 1С:УАТ
#    location:
#    extra-links: false
#    components:
#      - Romashka.Systems.VehicleManagement.EK_ASUFR3_1C_YAT.Vehicles
#      - Romashka.Systems.VehicleManagement.EK_ASUFR3_1C_YAT.ApplicationsRoadTransport
#      - Romashka.Systems.VehicleManagement.EK_ASUFR3_1C_YAT.PrimaryDocuments
#      - Romashka.Systems.VehicleManagement.EK_ASUFR3_1C_YAT.Waybills
#      - Romashka.Systems.FinancialManagement.EK_ASUFR3_1C_ERP

#  Romashka.Systems.VehicleManagement.EK_ASUFR3_1C_Etalon_YAT:
#    title: ЕК АСУФР-3. 1С:УАТ (эталон)
#    location:
#    extra-links: true
#    components:
#      - Romashka.Systems.VehicleManagement.EK_ASUFR3_1C_Etalon_YAT.*
#
#  Romashka.Systems.VehicleManagement.EK_ASUFR3_1C_Conslidate_YAT:
#    title: ЕК АСУФР-3. 1С:УАТ (консолидация)
#    location:
#    extra-links: true
#    components:
#      - Romashka.Systems.VehicleManagement.EK_ASUFR3_1C_Conslidate_YAT.*