#components:
#
#  # Управление архитектурой
#
#  Romashka.Systems.ArchitectureManagement.Dochub:
#    title: "Dochub"
#    entity: component
#    description:
#      "DocHub - инструмент описания архитектуры через код (Architecture as a code). Код архитектуры - ансамбль файлов на языках, решающих задачу описания архитектуры."
#    business_owners:
#      - Egorov Demid Nikitich
#    application_owner: Zvereva Ksenia Matveevna
#    budget_holder: Zakharova Vasilisa Artemovna
#    architect: Solovyova Vera Georgievna
#    extension:
#      type: external system
#      area: Технологический контур
#      state: Проектируется
#      state_update_date: 01.01.2023
#      development_platform: JavaScript
#      basic_solution: dochub
#      basic_solution_state: Развивается поставщиком
#      basic_solution_link: https://dochub.info/main
#      provider: Роман Пионтик
#      provider_type: Роман Пионтик
