components:

  Romashka.Systems:
    title: Приложения и сервисы
    entity: component
    extension:
      type: systems

aspects:

  CommonAspects:
    title: Базовые функции
    location: Базовые функции

  CommonAspects.ReferenceClassifiers:
    title: Эталонные классификаторы
    location: Эталонные классификаторы

  CommonAspects.ReferenceMDM:
    title: Эталонные НСИ
    location: Эталонные классификаторы

  CommonAspects.ReferenceSettings:
    title: Эталонные настройки
    location: Эталонные классификаторы

  CommonAspects.MonitoringFunctionality:
    title: Мониторинг функциональности
    location: Эталонные классификаторы

  CommonAspects.StatisticsManagement:
    title: Управление статистикой
    location: Эталонные классификаторы

  CommonAspects.InternalControlSystem:
    title: Система внутренних контролей
    location: Эталонные классификаторы

  CommonAspects.ConsolidatedStatements:
    title: Формирование консолидированной отчетности
    location: Эталонные классификаторы