components:

  Lutik.Systems.EnvironmentalHealthSafety:
    title: Охрана труда и окружающей среды, безопасность
    entity: component

contexts:

  Lutik.Systems.EnvironmentalHealthSafety:
    title: Финансовый контур
    location:
    extra-links: true
    components:
      - Lutik.Systems.EnvironmentalHealthSafety.*