components:

  Romashka.Systems.ReportingSystems:
    title: Консолидированная отчетность
    entity: component

contexts:

  # Контекст расчета з/п и управления персоналом

  Romashka.Systems.ReportingSystems:
    title: Консолидированная отчетность
    location: "Ромашка/Архитектурные схемы/Уровень 2/Консолидированная отчетность"
    extra-links: true
    components:
      - Romashka.Systems.ReportingSystems.*