#components:

  # Системы Финансового конутра

#  Romashka.Systems.FinancialManagement.EK_ASUFR3_1C_ERP:
#    title: ЕК АСУФР-3. 1С:ERP
#    entity: component
#    description:
#      "Единая корпоративная автоматизированная система предназначена для автоматизации следующих функциональных блоков – Бухгалтерский учет по разделам учета,
#       Налоговый учет, Управленческий учет по видам затрат, Функции казначейского контроля (казначейский учет), Учет по МСФО, Управление снабжением МТР,
#       Система внутренних контролей и Мониторинги функциональности"
#    business_owners:
#      - Egorov Demid Nikitich
#    application_owner: Zvereva Ksenia Matveevna
#    budget_holder: Zakharova Vasilisa Artemovna
#    architect: Solovyova Vera Georgievna
#    extension:
#      type: system
#      area: Финансовый контур
#      state: Проектируется
#      state_update_date: 01.01.2023
#      development_platform: "1С:Предприятие 8"
#      basic_solution: "1С:ERP, редакция 2.5"
#      basic_solution_state: Развивается поставщиком
#      basic_solution_link: https://solutions.1c.ru/catalog/1cerp
#      provider: ООО Ромашка
#      provider_type: Собственная разработка
#    aspects:
#      - FinancialManagement.RegulatedAccounting
#      - FinancialManagement.TaxAccounting
#      - FinancialManagement.ManagementAccounting
#      - FinancialManagement.IFRSAccounting
#      - FinancialManagement.TreasuryAccounting
#      - FinancialManagement.MTR
#      - CommonAspects.MonitoringFunctionality
#      - CommonAspects.StatisticsManagement
#      - CommonAspects.InternalControlSystem

#  Romashka.Systems.FinancialManagement.EK_ASUFR3_1C_Etalon_ERP:
#    title: ЕК АСУФР-3. 1С:ERP (эталон)
#    entity: component
#    description:
#      "Автоматизированная система предназначена для целей управления централизованной нормативно-справочной информацией и параметрическими настройками,
#       влияющими на функционирование «ЕК АСУФР-3. 1С:ERP», а также реализации функций моделирования и контроля над изменениями учетной политики с обес-печением
#       переноса выполненных изменений в «ЕК АСУФР-3. 1С:ERP». Дополнительно копия системы может использоваться для проведения обучения пользователей, например,
#       в процессе тиражирования или различных видов тестирования (функциональное, ре-грессионное и прочее)"
#    business_owners:
#      - Egorov Demid Nikitich
#    application_owner: Zvereva Ksenia Matveevna
#    budget_holder: Zakharova Vasilisa Artemovna
#    architect: Solovyova Vera Georgievna
#    extension:
#      type: system
#      area: Финансовый контур
#      state: Проектируется
#      state_update_date: 01.01.2023
#      development_platform: "1С:Предприятие 8"
#      basic_solution: "1С:ERP, редакция 2.5"
#      basic_solution_state: Развивается поставщиком
#      basic_solution_link: https://solutions.1c.ru/catalog/1cerp
#      provider: ООО Ромашка
#      provider_type: Собственная разработка
#      owner_name: Иванов И. И.
#      owner_email: fio@mail.ru
#    aspects:
#      - CommonAspects.ReferenceClassifiers
#      - CommonAspects.ReferenceMDM
#      - CommonAspects.ReferenceSettings

#  Romashka.Systems.FinancialManagement.EK_ASUFR3_1C_Conslidate_ERP:
#    title: ЕК АСУФР-3. 1С:ERP (консолидация)
#    entity: component
#    description:
#      "Автоматизированная система предназначена для целей управления централизованной нормативно-справочной информацией и параметрическими настройками,
#       влияющими на функционирование «ЕК АСУФР-3. 1С:ERP», а также реализации функций моделирования и контроля над изменениями учетной политики с
#       обеспечением переноса выполненных изменений в «ЕК АСУФР-3. 1С:ERP». Дополнительно копия системы может использоваться для проведения обучения
#       пользователей, например, в процессе тиражирования или различных видов тестирования (функциональное, ре-грессионное и прочее)"
#    business_owners:
#      - Egorov Demid Nikitich
#    application_owner: Zvereva Ksenia Matveevna
#    budget_holder: Zakharova Vasilisa Artemovna
#    architect: Solovyova Vera Georgievna
#    extension:
#      type: system
#      area: Финансовый контур
#      state: Проектируется
#      state_update_date: 01.01.2023
#      development_platform: "1С:Предприятие 8"
#      basic_solution: "1С:ERP, редакция 2.5"
#      basic_solution_state: Развивается поставщиком
#      basic_solution_link: https://solutions.1c.ru/catalog/1cerp
#      provider: ООО Ромашка
#      provider_type: Собственная разработка
#    aspects:
#      - CommonAspects.ConsolidatedStatements

#  Romashka.Systems.FinancialManagement.EK_ASUFR3_1C_MDM_ERP:
#    title: ЕК АСУФР-3. ЦНСИ
#    entity: component
#    description:
#      "Единая корпоративная платформа управление процессом ведения нормативно-справочной информации функциональных компонент ЕК АСУФР-3"
#    business_owners:
#      - Egorov Demid Nikitich
#    application_owner: Zvereva Ksenia Matveevna
#    budget_holder: Zakharova Vasilisa Artemovna
#    architect: Solovyova Vera Georgievna
#    extension:
#      type: system
#      area: Финансовый контур
#      state: Проектируется
#      state_update_date: 01.01.2023
#      development_platform: "1С:Предприятие 8"
#      basic_solution: "1С:MDM"
#      basic_solution_state: Развивается поставщиком
#      basic_solution_link: https://solutions.1c.ru/catalog/mdm
#      provider: ООО "Разработчик 1С"
#      provider_type: Заказная разработка
#
#    aspects:
#      - CommonAspects.ReferenceMDM